### ISSUE TITLE
Maybe it's a global issue...I can't use the cmd+v 

### ISSUE THREAD

**Issue by fake110** [LanyuanXiaoyao-Studio/SearchX#6]
Seems I can't use the Copy (cmd+c) & Paste (cmd+v)?

SW:0.2.2
OS:Big Sur 11.1

**Comment by lanyuanxiaoyao** [comment]
Fixed. [0.2.3](https://github.com/LanyuanXiaoyao-Studio/SearchX/releases/tag/0.2.3)
